---
title: "Week 2 Assignment"
author: "Alina Simakova"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
###Loading data
```{r, message=FALSE, warning=FALSE}
data <- read.csv("activity.csv", sep = ",")
data1 <- data
data1$date <- as.Date(data$date)

library(lubridate)

data1$days <- day(data1$date)
```

###Mean of steps per day

```{r, message=FALSE, warning=FALSE}
library(dplyr)

total_steps_per_day <- data1 %>%
    group_by(days) %>%
    summarise(steps = sum(steps))


hist(total_steps_per_day$steps, xlab = "Steps", main = "Total number of steps taken each day", col = "blue")

summary(total_steps_per_day$steps)
```

Mean value is 21152 steps per day and median is 21782.



```{r}
total_steps_per_interval <- data1 %>%
    group_by(interval) %>%
    summarise(mean_steps = mean(steps, na.rm = T))

plot(x = total_steps_per_interval$interval, y = total_steps_per_interval$mean_steps, type = "l",
     xlab = "5-minute interval", ylab = "Average number of steps",
     main = "Average steps of the 5-minute intervals", lwd = 2)

max_steps <- as.double(which.max(total_steps_per_interval$mean_steps))

total_steps_per_interval[max_steps,]

```

The  maximum number of steps in  interval #835. 

###Imputing missing values

```{r}
total_NAs <- sum(is.na(data$steps))
total_NAs

data_filled <- data1
data_filled$steps <- ifelse(is.na(data_filled$steps), round(total_steps_per_interval$mean_steps), data_filled$steps)

hist(tapply(data_filled$steps, data_filled$date, sum), xlab = "Steps",
     main = "Total number of steps taken each day with NA filled", col = "green")

total_steps_per_day_filled <- data_filled %>%
    group_by(days) %>%
    summarise(steps = sum(steps))

summary(total_steps_per_day_filled)
```

New mean and median are equal 21184 and 21641 respectively. There is no such a difference with non-filled data.

###Activity patterns between weekdays and weekends

```{r, warning=FALSE, message=FALSE}
week <- format(data_filled$date, "%u")
factor_week <- factor(ifelse(week > 5, "weekend", "weekday"))
data_filled$week <- factor_week

weekly_split <- split(data_filled, data_filled$week)
weekly_mean <- sapply(weekly_split, function(x) with(x, tapply(steps, interval, mean)))

library(data.table)

weekly_mean_melt <- data.table::melt(weekly_mean)
names(weekly_mean_melt) <- c("interval", "week", "steps")

library(ggplot2)

ggplot(weekly_mean_melt, aes(x = interval, y = steps)) +
        geom_line(pch = 20, col = "blue", lwd = 1) +
        facet_wrap(~ week, nrow = 2)
```

